### ISSUE TITLE
Add new aggregates to /v1/aggregate-results

### ISSUE THREAD

**Issue by bherr2** [x-atlas-consortia/hra-api#1]
* \# Publications
* \# Tissue Data Providers (is this consortium or data_provider in the data?)
* \# Extraction Sites

See original issue [here](https://github.com/hubmapconsortium/ccf-ui/issues/1164)

**Comment by bherr2** [comment]
@andreasbueckle what was the thinking on tissue data providers? There are two metadata items that could be counted here.

**Comment by bherr2** [comment]
Will re-open if the request comes up again.

**Comment by andreasbueckle** [comment]
@bherr2 
Could have both consortium and data_provider? We regularly report both numbers in reports, talks, papers.

**Comment by bherr2** [comment]
Adding those two plus # publications really starts to impede display. See
![image](https://github.com/user-attachments/assets/4fbdd4ce-8cc6-4f33-b784-40f95a1cd114)

This is probably one of those things that needs some UX work to keep it viable.

**Comment by bherr2** [comment]
No, but I'll go ahead and add it anyway. I realized we already list the number of tissue data providers, just need to add # Consortia and # Publications

**Comment by bherr2** [comment]
I'm going to leave out # publications for now as there is not great support for it right now (every EUI instance, except for HRApop would show 0 publications which is wrong).
